export const DEFAULT_TEST_CASES = [
  {
    id: "T1",
    category: "safe",
    input: "Please send the report by EOD.",
    expected_tone: "direct",
    expected_hidden_signal: "none",
    expected_risk_min: 0,
    expected_risk_max: 25,
    notes: "",
  },
  {
    id: "T2",
    category: "safe",
    input: "I will review and get back to you.",
    expected_tone: "neutral",
    expected_hidden_signal: "none",
    expected_risk_min: 0,
    expected_risk_max: 25,
    notes: "",
  },
  {
    id: "T3",
    category: "safe",
    input: "Let's connect tomorrow to discuss.",
    expected_tone: "polite",
    expected_hidden_signal: "none",
    expected_risk_min: 0,
    expected_risk_max: 25,
    notes: "",
  },
];