export const DEFAULT_TEST_CASES = [
  {
    id: "TC1",
    category: "safe",
    input: "I need an answer today.",
    expected_tone: "tense",
    expected_hidden_signal: "none",
    expected_regret_band: "medium",
    expected_emotional_pressure_band: "low",
    expected_reply_vibe: "poor",
    expected_send_verdict: "send",
    expected_rewrite_present: "no",
    expected_advisory_present: "yes",
    notes: "Consumer screenshot baseline.",
  },
  {
    id: "TC2",
    category: "safe",
    input: "Please send the report by 4 PM. Thank you.",
    expected_tone: "polite",
    expected_hidden_signal: "none",
    expected_regret_band: "low",
    expected_emotional_pressure_band: "low",
    expected_reply_vibe: "medium",
    expected_send_verdict: "send",
    expected_rewrite_present: "no",
    expected_advisory_present: "yes",
    notes: "",
  },
  {
    id: "TC3",
    category: "passive_aggressive",
    input: "Fine. Do whatever you want.",
    expected_tone: "passive aggressive",
    expected_hidden_signal: "passive aggression",
    expected_regret_band: "medium",
    expected_emotional_pressure_band: "medium",
    expected_reply_vibe: "poor",
    expected_send_verdict: "review",
    expected_rewrite_present: "yes",
    expected_advisory_present: "yes",
    notes: "This should still fail on verdict until decision mapping is tightened.",
  },
  {
    id: "TC4",
    category: "emotional_pressure",
    input: "After everything I did for you, this is how you respond?",
    expected_tone: "manipulative",
    expected_hidden_signal: "emotional",
    expected_regret_band: "high",
    expected_emotional_pressure_band: "high",
    expected_reply_vibe: "medium",
    expected_send_verdict: "review",
    expected_rewrite_present: "yes",
    expected_advisory_present: "yes",
    notes: "",
  },
  {
    id: "TC5",
    category: "safe",
    input: "Can we talk about this calmly?",
    expected_tone: "calm",
    expected_hidden_signal: "none",
    expected_regret_band: "low",
    expected_emotional_pressure_band: "low",
    expected_reply_vibe: "medium",
    expected_send_verdict: "send",
    expected_rewrite_present: "no",
    expected_advisory_present: "yes",
    notes: "",
  },
  {
    id: "TC6",
    category: "aggressive",
    input: "You always do this. I am done explaining.",
    expected_tone: "accusatory",
    expected_hidden_signal: "pressure",
    expected_regret_band: "high",
    expected_emotional_pressure_band: "medium",
    expected_reply_vibe: "medium",
    expected_send_verdict: "review",
    expected_rewrite_present: "yes",
    expected_advisory_present: "yes",
    notes: "Should still fail on verdict until decision mapping is improved.",
  },
];